function [RptgenML_CReport1] = buildreport
%BUILDREPORT
 
%  Auto-generated by MATLAB on 14-Jan-2017 09:42:28
 
% Create RptgenML.CReport
RptgenML_CReport1 = RptgenML.CReport('Format','dom-docx',...
'Stylesheet','default-rg-docx');
% setedit(RptgenML_CReport1);
 
% Create rptgen.cfr_section
rptgen_cfr_section1 = rptgen.cfr_section('StyleName','rgChapterTitle',...
'SectionTitle','Section 1');
setParent(rptgen_cfr_section1,RptgenML_CReport1);
 
% Create rptgen.cfr_image
rptgen_cfr_image1 = rptgen.cfr_image('MaxViewportSize',[7 9]);
setParent(rptgen_cfr_image1,rptgen_cfr_section1);
 
% Create rptgen.cfr_section
rptgen_cfr_section2 = rptgen.cfr_section('StyleName','rgChapterTitle',...
'SectionTitle','Section 2');
setParent(rptgen_cfr_section2,RptgenML_CReport1);
 
% Create rptgen.cfr_image
rptgen_cfr_image2 = rptgen.cfr_image('MaxViewportSize',[7 9]);
setParent(rptgen_cfr_image2,rptgen_cfr_section2);
 
% Create rptgen.cfr_section
rptgen_cfr_section3 = rptgen.cfr_section('StyleName','rgChapterTitle',...
'SectionTitle','Section 3');
setParent(rptgen_cfr_section3,RptgenML_CReport1);
 
